global:
  scrape_interval: '5s'
  evaluation_interval: '5s'
  
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

rule_files:
  # - "first_rules.yml"

scrape_configs:
  - job_name: 'blockatlas'
    static_configs:
      - targets: ['{{.APP_URL}}']
