{
 "title": "HTTP Clients",
 "tags": [ "Client" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(client_http_request_count_total, job)"
   },
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "endpoint",
    "label": "Endpoint",
    "query": "label_values(client_http_request_count_total{endpoint!~\"/metrics|/favicon.ico\"}, endpoint)"
   },
   {
    "name": "method",
    "label": "Method",
    "query": "label_values(client_http_request_count_total, method)"
   },
   {
    "name": "status",
    "label": "Status",
    "query": "label_values(client_http_request_count_total, status)"
   },
   { "name": "quantile", "label": "Quantile", "query": "0.95,0.75,0.25" }
  ]
 },
 "panels": [
  {
   "title": "Requests QPS",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(client_http_request_count_total{job=~\"$job\", endpoint=~\"$endpoint\", method=~\"$method\", status=~\"$status\"}[$interval])",
     "legendFormat": "{{ endpoint }}"
    }
   ]
  },
  {
   "title": "Duration per request",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(client_http_request_duration_seconds_sum{job=~\"$job\", endpoint=~\"$endpoint\", method=~\"$method\", status=~\"$status\"}[$interval])\r\n/\r\nrate(client_http_request_duration_seconds_count{job=~\"$job\", endpoint=~\"$endpoint\", method=~\"$method\", status=~\"$status\"}[$interval])",
     "legendFormat": "{{ endpoint }}"
    }
   ]
  },
  {
   "title": "Request size(bytes) per second",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(client_http_request_size_bytes_sum{job=~\"$job\", endpoint=~\"$endpoint\", method=~\"$method\", status=~\"$status\"}[$interval])\n/\nrate(client_http_request_size_bytes_count{job=~\"$job\", endpoint=~\"$endpoint\", method=~\"$method\", status=~\"$status\"}[$interval])",
     "legendFormat": "{{ endpoint }}"
    }
   ]
  },
  {
   "title": "Response size(bytes) per second",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(client_http_response_size_bytes_sum{job=~\"$job\", endpoint=~\"$endpoint\", method=~\"$method\", status=~\"$status\"}[$interval])\n/\nrate(client_http_response_size_bytes_count{job=~\"$job\", endpoint=~\"$endpoint\", method=~\"$method\", status=~\"$status\"}[$interval])",
     "legendFormat": "{{ endpoint }}"
    }
   ]
  },
  {
   "title": "Quantile of requests",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($quantile, sum(rate(client_http_request_duration_seconds_bucket{job=~\"$job\", endpoint=~\"$endpoint\", method=~\"$method\", status=~\"$status\"}[$interval])) by (le))",
     "legendFormat": "{{ endpoint }}"
    }
   ]
  }
 ]
}